### ISSUE TITLE
Support for group membership?

### ISSUE THREAD

**Issue by pcolmer** [ravikiranj/discourse-sso-python-ldap#1]
Hi

Thank you for sharing this code. It has really helped me get Discourse up and running with our LDAP server.

According to https://meta.discourse.org/t/official-single-sign-on-for-discourse/13045, there is support for being able to specify groups that the user is in. How can your project be extended to allow groups to be specified?

Thanks.

**Comment by ravikiranj** [comment]
Hi @pcolmer,
    I'm terribly sorry for the delayed reply. After glancing over the official doc, we can supply the "add_groups" and "remove_groups" payload in https://github.com/ravikiranj/discourse-sso-python-ldap/blob/master/auth.py#L96.

For example,
```python
    add_groups = ["group1", "group2"]
    remove_groups = ["group3"]
    min_req_credentials = {
        "external_id": result["external_id"],
        "nonce": nonce,
        "email": result["email"],
        "name": result["name"],
        "username": result["username"],
        "add_groups": ",".join(add_groups),
        "remove_groups": ",".join(remove_groups)
    }
```

I can probably parse a config file with the optional settings and then merge them to the min_req_credentials dict if it's easier.

Do you want to submit a pull request for the above change?

**Comment by ravikiranj** [comment]
Closing this one due to no response from the poster. Please feel free to submit a PR.
